Select 
A.ID,
A.NUMERO,
A.NUMEROS,
A.FECHA,
A.HORA,
A.CODIGOMESA,
A.NUMEROMESA,
A.CODIGOSALONERO,
A.USUARIOSALONERO,
A.NOMBRESALONERO,
A.CODIGOCLIENTE,
A.NOMBRECLIENTE,
A.SUBTOTAL,
A.DESCUENTOP,
A.DESCUENTOM,
A.IVAP,
A.IVAM,
A.ISP,
A.ISM,
A.TRANSPORTE,
A.TOTAL,
A.TOTALGRAVADO,
A.TOTALEXCENTO,
A.CODIGOESTADO,
A.CODIGOFORMAPAGO,
A.CODIGOMONEDA,
A.TIPOCAMBIO,
A.SERIE,
A.CODIGOIMPRESA,
A.NUMERODOC,
A.FECHAVENCIMIENTO,
A.CODIGOTIPO,
A.SALDO,
A.CARCREDITO,
A.CARCONTADO,
A.CODIGOVENDEDOR,
A.NOMBREVENDEDOR,
A.NUMEROPROFORMA,
A.NUMEROSPROFORMA,
A.PAGOCON,
A.CAMBIO,
A.EFECTIVO,
A.TARJETA,
A.TRANSFERENCIA,
A.CHEQUE,
A.IdCliente,
A.IdVendedor,
A.NUMERONotaCredito,
A.Kilos,
B.Nombre As EstadoNombre,
C.DIRECCION As ClienteDireccion,
C.TELEFONO1 As ClienteTelefono1,
C.CONTACTONOMBRE As ClienteContactoNombre
From TB_FACTURASCLIENTESENCABEZADO A
Left Join TB_ESTADOS B on A.CODIGOESTADO=B.Id
Left Join TB_Clientes C on A.IdCliente=C.Id
Where (A.Fecha >= '2019-07-08'
 And 
A.Fecha <= '2019-07-08')



Order By  A.Fecha DESC, A.Hora DESC


